platform :ios,'7.0'
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage'
pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-cocoapods.git'

pod 'BmobSDK'
pod 'ShareSDK2'
pod 'MOBFoundation'
pod 'ShareSDK2/UI'
pod 'ShareSDK2/UI/iPhoneDefault'
pod 'ShareSDK2/Connection/SinaWeibo'
pod 'ShareSDK2/Connection/WeChat'
pod 'ShareSDK2/Connection/QQ'
pod 'ShareSDK2/Connection/QZone'

