platform :ios,'7.0'
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage'
pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'
pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-cocoapods.git'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
 pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
 pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'Bmob:
